//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZunTzu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZunTzu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AboutZunTzu {
            get {
                object obj = ResourceManager.GetObject("AboutZunTzu", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoRecover.
        /// </summary>
        internal static string AutosaveDialogCaption {
            get {
                return ResourceManager.GetString("AutosaveDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last session has not exited normally. Restore autosaved game?.
        /// </summary>
        internal static string AutosaveDialogText {
            get {
                return ResourceManager.GetString("AutosaveDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t restore: no autosave file was found..
        /// </summary>
        internal static string AutosaveNotFound {
            get {
                return ResourceManager.GetString("AutosaveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This board is hidden.
        /// </summary>
        internal static string BoardIsHidden {
            get {
                return ResourceManager.GetString("BoardIsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start server: {0}.
        /// </summary>
        internal static string CantStartServer {
            get {
                return ResourceManager.GetString("CantStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start server: port {0} is already in use. Try again with a different port..
        /// </summary>
        internal static string CantStartServerInvalidDeviceAddress {
            get {
                return ResourceManager.GetString("CantStartServerInvalidDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of type {0}: {1}.
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip: {0} port: {1}.
        /// </summary>
        internal static string ConnectionData {
            get {
                return ResourceManager.GetString("ConnectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address and port have been copied to the clipboard..
        /// </summary>
        internal static string ConnectionDataCopiedToClipboard {
            get {
                return ResourceManager.GetString("ConnectionDataCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection request was rejected by host..
        /// </summary>
        internal static string ConnectionFailureHostRejectedConnection {
            get {
                return ResourceManager.GetString("ConnectionFailureHostRejectedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No communication link was established..
        /// </summary>
        internal static string ConnectionFailureNoConnection {
            get {
                return ResourceManager.GetString("ConnectionFailureNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to connect to a nonhost computer..
        /// </summary>
        internal static string ConnectionFailureNotHost {
            get {
                return ResourceManager.GetString("ConnectionFailureNotHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request to connect to the host failed..
        /// </summary>
        internal static string ConnectionFailureOther {
            get {
                return ResourceManager.GetString("ConnectionFailureOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of players for the session has been reached..
        /// </summary>
        internal static string ConnectionFailureSessionFull {
            get {
                return ResourceManager.GetString("ConnectionFailureSessionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection request has timed out..
        /// </summary>
        internal static string ConnectionFailureTimeOut {
            get {
                return ResourceManager.GetString("ConnectionFailureTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ConnectivityCancelLimited {
            get {
                return ResourceManager.GetString("ConnectivityCancelLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ConnectivityCancelNoEgress {
            get {
                return ResourceManager.GetString("ConnectivityCancelNoEgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ConnectivityCancelNoIngress {
            get {
                return ResourceManager.GetString("ConnectivityCancelNoIngress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ConnectivityCancelNoInternet {
            get {
                return ResourceManager.GetString("ConnectivityCancelNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConnectivityCancelPortInUse {
            get {
                return ResourceManager.GetString("ConnectivityCancelPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited connectivity.
        /// </summary>
        internal static string ConnectivityCaptionLimited {
            get {
                return ResourceManager.GetString("ConnectivityCaptionLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A firewall is blocking ZunTzu.
        /// </summary>
        internal static string ConnectivityCaptionNoEgress {
            get {
                return ResourceManager.GetString("ConnectivityCaptionNoEgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A firewall is blocking ZunTzu.
        /// </summary>
        internal static string ConnectivityCaptionNoIngress {
            get {
                return ResourceManager.GetString("ConnectivityCaptionNoIngress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        internal static string ConnectivityCaptionNoInternet {
            get {
                return ResourceManager.GetString("ConnectivityCaptionNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port in use.
        /// </summary>
        internal static string ConnectivityCaptionPortInUse {
            get {
                return ResourceManager.GetString("ConnectivityCaptionPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host anyway.
        /// </summary>
        internal static string ConnectivityOkLimited {
            get {
                return ResourceManager.GetString("ConnectivityOkLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host anyway.
        /// </summary>
        internal static string ConnectivityOkNoEgress {
            get {
                return ResourceManager.GetString("ConnectivityOkNoEgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host anyway.
        /// </summary>
        internal static string ConnectivityOkNoIngress {
            get {
                return ResourceManager.GetString("ConnectivityOkNoIngress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host anyway.
        /// </summary>
        internal static string ConnectivityOkNoInternet {
            get {
                return ResourceManager.GetString("ConnectivityOkNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string ConnectivityOkPortInUse {
            get {
                return ResourceManager.GetString("ConnectivityOkPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZunTzu&apos;s central server is momentarily out of service. Players may be unable to join..
        /// </summary>
        internal static string ConnectivityTextLimited {
            get {
                return ResourceManager.GetString("ConnectivityTextLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your firewall settings to let ZunTzu send data to the Internet..
        /// </summary>
        internal static string ConnectivityTextNoEgress {
            get {
                return ResourceManager.GetString("ConnectivityTextNoEgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your firewall settings to let ZunTzu receive connection requests from the Internet..
        /// </summary>
        internal static string ConnectivityTextNoIngress {
            get {
                return ResourceManager.GetString("ConnectivityTextNoIngress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only players on your local network will be able to join..
        /// </summary>
        internal static string ConnectivityTextNoInternet {
            get {
                return ResourceManager.GetString("ConnectivityTextNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That Internet port is reserved by another program. Try again with a different port number..
        /// </summary>
        internal static string ConnectivityTextPortInUse {
            get {
                return ResourceManager.GetString("ConnectivityTextPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command ignored. You need to disconnect first..
        /// </summary>
        internal static string DisconnectFirst {
            get {
                return ResourceManager.GetString("DisconnectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZunTzu files (*.ztb;*.ztg;*.zts)|*.ztb;*.ztg;*.zts|All files|*.*.
        /// </summary>
        internal static string FileOpenFilter {
            get {
                return ResourceManager.GetString("FileOpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZunTzu games (*.ztg)|*.ztg|All files|*.*.
        /// </summary>
        internal static string FileSaveAsFilter {
            get {
                return ResourceManager.GetString("FileSaveAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game box &quot;{0}&quot; is already opened..
        /// </summary>
        internal static string GameBoxAlreadyOpened {
            get {
                return ResourceManager.GetString("GameBoxAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}..
        /// </summary>
        internal static string GameBoxError00 {
            get {
                return ResourceManager.GetString("GameBoxError00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive doesn&apos;t contain a &quot;game-box.xml&quot; file..
        /// </summary>
        internal static string GameBoxError01 {
            get {
                return ResourceManager.GetString("GameBoxError01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game-box.xml doesn&apos;t begin with a &quot;&lt;?xml &quot; line followed by &quot;&lt;game-box &quot;..
        /// </summary>
        internal static string GameBoxError02 {
            get {
                return ResourceManager.GetString("GameBoxError02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attributes &quot;{1}&quot; and &quot;{2}&quot; are incompatible..
        /// </summary>
        internal static string GameBoxError03 {
            get {
                return ResourceManager.GetString("GameBoxError03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is deprecated..
        /// </summary>
        internal static string GameBoxError04 {
            get {
                return ResourceManager.GetString("GameBoxError04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is invalid without attribute &quot;{2}&quot;..
        /// </summary>
        internal static string GameBoxError05 {
            get {
                return ResourceManager.GetString("GameBoxError05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is irrelevant for a card section..
        /// </summary>
        internal static string GameBoxError06 {
            get {
                return ResourceManager.GetString("GameBoxError06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is irrelevant for a counter or terrain section..
        /// </summary>
        internal static string GameBoxError07 {
            get {
                return ResourceManager.GetString("GameBoxError07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; refers to a file that can&apos;t be found in the game box archive..
        /// </summary>
        internal static string GameBoxError08 {
            get {
                return ResourceManager.GetString("GameBoxError08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; should end with &quot;{2}&quot;..
        /// </summary>
        internal static string GameBoxError09 {
            get {
                return ResourceManager.GetString("GameBoxError09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; should end with &quot;.jpg&quot; or &quot;.png&quot;..
        /// </summary>
        internal static string GameBoxError10 {
            get {
                return ResourceManager.GetString("GameBoxError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is irrelevant for a terrain section..
        /// </summary>
        internal static string GameBoxError11 {
            get {
                return ResourceManager.GetString("GameBoxError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: board &quot;{1}&quot; is defined twice..
        /// </summary>
        internal static string GameBoxError12 {
            get {
                return ResourceManager.GetString("GameBoxError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;{1}&quot; is defined twice..
        /// </summary>
        internal static string GameBoxError13 {
            get {
                return ResourceManager.GetString("GameBoxError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected end-tag &quot;&lt;/{1}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError14 {
            get {
                return ResourceManager.GetString("GameBoxError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected &quot;&lt;dice &quot; or &quot;&lt;/dice-hand&gt;&quot;..
        /// </summary>
        internal static string GameBoxError15 {
            get {
                return ResourceManager.GetString("GameBoxError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected &quot;&lt;dice-hand &quot;, &quot;&lt;map &quot;, &quot;&lt;counter-sheet &quot;, &quot;&lt;terrain-sheet &quot; or &quot;&lt;/game-box&gt;&quot;..
        /// </summary>
        internal static string GameBoxError16 {
            get {
                return ResourceManager.GetString("GameBoxError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected section definition or &quot;&lt;/{1}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError17 {
            get {
                return ResourceManager.GetString("GameBoxError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: found &quot;&lt;/{1}&gt;&quot; but expected &quot;&lt;/{2}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError18 {
            get {
                return ResourceManager.GetString("GameBoxError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: found data after final end-tag &quot;&lt;/{1}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError19 {
            get {
                return ResourceManager.GetString("GameBoxError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: invalid attribute &quot;{1}&quot; because no back image..
        /// </summary>
        internal static string GameBoxError20 {
            get {
                return ResourceManager.GetString("GameBoxError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: invalid value &quot;{1}&quot; for attribute &quot;{2}&quot; because no back image..
        /// </summary>
        internal static string GameBoxError21 {
            get {
                return ResourceManager.GetString("GameBoxError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: location attributes &quot;front-...&quot; or &quot;back-...&quot; missing..
        /// </summary>
        internal static string GameBoxError22 {
            get {
                return ResourceManager.GetString("GameBoxError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: mandatory attribute &quot;{1}&quot; missing..
        /// </summary>
        internal static string GameBoxError23 {
            get {
                return ResourceManager.GetString("GameBoxError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: mandatory attribute &quot;{1}&quot; present but empty..
        /// </summary>
        internal static string GameBoxError24 {
            get {
                return ResourceManager.GetString("GameBoxError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: section type is &quot;{1}&quot; so attribute &quot;{2}&quot; is invalid..
        /// </summary>
        internal static string GameBoxError25 {
            get {
                return ResourceManager.GetString("GameBoxError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: section type is &quot;{1}&quot; so attribute &quot;{2}&quot; is required..
        /// </summary>
        internal static string GameBoxError26 {
            get {
                return ResourceManager.GetString("GameBoxError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: invalid section type for this sheet..
        /// </summary>
        internal static string GameBoxError27 {
            get {
                return ResourceManager.GetString("GameBoxError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: unsupported attribute &quot;{1}&quot;..
        /// </summary>
        internal static string GameBoxError28 {
            get {
                return ResourceManager.GetString("GameBoxError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: unsupported tag &quot;&lt;{1} &quot;..
        /// </summary>
        internal static string GameBoxError29 {
            get {
                return ResourceManager.GetString("GameBoxError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : file not referenced in game-box.xml..
        /// </summary>
        internal static string GameBoxError30 {
            get {
                return ResourceManager.GetString("GameBoxError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : scenario file doesn&apos;t begin with a &quot;&lt;?xml &quot; line followed by &quot;&lt;game &quot;..
        /// </summary>
        internal static string GameBoxError31 {
            get {
                return ResourceManager.GetString("GameBoxError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected &quot;&lt;layout &quot;, &quot;&lt;hand &quot; or &quot;&lt;/game&gt;&quot;..
        /// </summary>
        internal static string GameBoxError32 {
            get {
                return ResourceManager.GetString("GameBoxError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected counter definition or &quot;&lt;/{1}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError33 {
            get {
                return ResourceManager.GetString("GameBoxError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: expected stack definition or &quot;&lt;/{1}&gt;&quot;..
        /// </summary>
        internal static string GameBoxError34 {
            get {
                return ResourceManager.GetString("GameBoxError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: visible board defined twice..
        /// </summary>
        internal static string GameBoxError35 {
            get {
                return ResourceManager.GetString("GameBoxError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: attribute &quot;board&quot; refers to an undefined board &quot;{1}&quot;..
        /// </summary>
        internal static string GameBoxError36 {
            get {
                return ResourceManager.GetString("GameBoxError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: board &quot;{1}&quot; wrongly assumed to be double-sided..
        /// </summary>
        internal static string GameBoxError37 {
            get {
                return ResourceManager.GetString("GameBoxError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: stack with no counter..
        /// </summary>
        internal static string GameBoxError38 {
            get {
                return ResourceManager.GetString("GameBoxError38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: board defined as private..
        /// </summary>
        internal static string GameBoxError39 {
            get {
                return ResourceManager.GetString("GameBoxError39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: non-empty private hand content..
        /// </summary>
        internal static string GameBoxError40 {
            get {
                return ResourceManager.GetString("GameBoxError40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : not a valid image file..
        /// </summary>
        internal static string GameBoxError41 {
            get {
                return ResourceManager.GetString("GameBoxError41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: mask size doesn&apos;t match image size..
        /// </summary>
        internal static string GameBoxError42 {
            get {
                return ResourceManager.GetString("GameBoxError42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: invalid value &quot;{1}&quot; for attribute &quot;{2}&quot;..
        /// </summary>
        internal static string GameBoxError43 {
            get {
                return ResourceManager.GetString("GameBoxError43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , line {0}: mandatory attribute &quot;board&quot; or &quot;tab&quot; missing..
        /// </summary>
        internal static string GameBoxError44 {
            get {
                return ResourceManager.GetString("GameBoxError44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game box file &quot;{0}&quot; has been deleted or moved..
        /// </summary>
        internal static string GameBoxFileMoved {
            get {
                return ResourceManager.GetString("GameBoxFileMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game box &quot;{0}&quot; was not found in the library..
        /// </summary>
        internal static string GameBoxNotFound {
            get {
                return ResourceManager.GetString("GameBoxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game box &quot;{0}&quot; opened..
        /// </summary>
        internal static string GameBoxOpened {
            get {
                return ResourceManager.GetString("GameBoxOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved..
        /// </summary>
        internal static string GameSaved {
            get {
                return ResourceManager.GetString("GameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        internal static string HintFlip {
            get {
                return ResourceManager.GetString("HintFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string HintRotate {
            get {
                return ResourceManager.GetString("HintRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan &amp; Scroll.
        /// </summary>
        internal static string HintScroll {
            get {
                return ResourceManager.GetString("HintScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string HintZoom {
            get {
                return ResourceManager.GetString("HintZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host has left game..
        /// </summary>
        internal static string HostHasLeft {
            get {
                return ResourceManager.GetString("HostHasLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command: {0}.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters for {0} command. Usage: {1}.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZunTzu game boxes (*.ztb)|*.ztb.
        /// </summary>
        internal static string LibraryAddFilter {
            get {
                return ResourceManager.GetString("LibraryAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading graphics....
        /// </summary>
        internal static string LoadingGraphics {
            get {
                return ResourceManager.GetString("LoadingGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ZunTzu....
        /// </summary>
        internal static string MenuAboutZunTzu {
            get {
                return ResourceManager.GetString("MenuAboutZunTzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        internal static string MenuConnect {
            get {
                return ResourceManager.GetString("MenuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string MenuDisconnect {
            get {
                return ResourceManager.GetString("MenuDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display....
        /// </summary>
        internal static string MenuDisplay {
            get {
                return ResourceManager.GetString("MenuDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host....
        /// </summary>
        internal static string MenuHost {
            get {
                return ResourceManager.GetString("MenuHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Library....
        /// </summary>
        internal static string MenuLibrary {
            get {
                return ResourceManager.GetString("MenuLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string MenuMultiplayer {
            get {
                return ResourceManager.GetString("MenuMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        internal static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Scenario....
        /// </summary>
        internal static string MenuOpenScenario {
            get {
                return ResourceManager.GetString("MenuOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player....
        /// </summary>
        internal static string MenuPlayer {
            get {
                return ResourceManager.GetString("MenuPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string MenuQuestionMark {
            get {
                return ResourceManager.GetString("MenuQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video....
        /// </summary>
        internal static string MenuVideo {
            get {
                return ResourceManager.GetString("MenuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio....
        /// </summary>
        internal static string MenuVoice {
            get {
                return ResourceManager.GetString("MenuVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game to save..
        /// </summary>
        internal static string NoGameToSave {
            get {
                return ResourceManager.GetString("NoGameToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session can&apos;t be joined from the Internet. Check your Internet connection and your firewall settings..
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command doesn&apos;t allow parameters..
        /// </summary>
        internal static string NoParameterSupported {
            get {
                return ResourceManager.GetString("NoParameterSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command ignored. You are not connected..
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command ignored. You must be hosting to run this command..
        /// </summary>
        internal static string NotHosting {
            get {
                return ResourceManager.GetString("NotHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has joined the game..
        /// </summary>
        internal static string PlayerHasJoined {
            get {
                return ResourceManager.GetString("PlayerHasJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has left game..
        /// </summary>
        internal static string PlayerHasLeft {
            get {
                return ResourceManager.GetString("PlayerHasLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} is now known as {1}..
        /// </summary>
        internal static string PlayerRenamed {
            get {
                return ResourceManager.GetString("PlayerRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitNoSavingRequiredButton {
            get {
                return ResourceManager.GetString("QuitNoSavingRequiredButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit?.
        /// </summary>
        internal static string QuitNoSavingRequiredPrompt {
            get {
                return ResourceManager.GetString("QuitNoSavingRequiredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as desktop.
        /// </summary>
        internal static string SameAsDesktop {
            get {
                return ResourceManager.GetString("SameAsDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players can join from the Internet using address {0} and port {1}..
        /// </summary>
        internal static string ServerListeningNatTraversalDisabled {
            get {
                return ResourceManager.GetString("ServerListeningNatTraversalDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players can join from the Internet using session code {0}..
        /// </summary>
        internal static string ServerListeningNatTraversalEnabled {
            get {
                return ResourceManager.GetString("ServerListeningNatTraversalEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Kbps per stream.
        /// </summary>
        internal static string ServerModeForwardingAdpcm {
            get {
                return ResourceManager.GetString("ServerModeForwardingAdpcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 Kbps per stream.
        /// </summary>
        internal static string ServerModeForwardingGsm {
            get {
                return ResourceManager.GetString("ServerModeForwardingGsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Kbps mixed.
        /// </summary>
        internal static string ServerModeMixingAdpcm {
            get {
                return ResourceManager.GetString("ServerModeMixingAdpcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 Kbps mixed.
        /// </summary>
        internal static string ServerModeMixingGsm {
            get {
                return ResourceManager.GetString("ServerModeMixingGsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session code has been copied to the clipboard..
        /// </summary>
        internal static string SessionIdCopiedToClipboard {
            get {
                return ResourceManager.GetString("SessionIdCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Esc).
        /// </summary>
        internal static string ToolTipClose {
            get {
                return ResourceManager.GetString("ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide board.
        /// </summary>
        internal static string ToolTipHideBoard {
            get {
                return ResourceManager.GetString("ToolTipHideBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide hand.
        /// </summary>
        internal static string ToolTipHideHand {
            get {
                return ResourceManager.GetString("ToolTipHideHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string ToolTipInvert {
            get {
                return ResourceManager.GetString("ToolTipInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string ToolTipPin {
            get {
                return ResourceManager.GetString("ToolTipPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpunch (Del).
        /// </summary>
        internal static string ToolTipRecycle {
            get {
                return ResourceManager.GetString("ToolTipRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        internal static string ToolTipRedo {
            get {
                return ResourceManager.GetString("ToolTipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal board.
        /// </summary>
        internal static string ToolTipRevealBoard {
            get {
                return ResourceManager.GetString("ToolTipRevealBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hand.
        /// </summary>
        internal static string ToolTipShowHand {
            get {
                return ResourceManager.GetString("ToolTipShowHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu (Esc).
        /// </summary>
        internal static string ToolTipShowMenu {
            get {
                return ResourceManager.GetString("ToolTipShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string ToolTipShuffle {
            get {
                return ResourceManager.GetString("ToolTipShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacking.
        /// </summary>
        internal static string ToolTipStacking {
            get {
                return ResourceManager.GetString("ToolTipStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit terrains.
        /// </summary>
        internal static string ToolTipTerrainMode {
            get {
                return ResourceManager.GetString("ToolTipTerrainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        internal static string ToolTipUndo {
            get {
                return ResourceManager.GetString("ToolTipUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        internal static string ToolTipUnpin {
            get {
                return ResourceManager.GetString("ToolTipUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to game. Game box &quot;{0}&quot; was not found in the library..
        /// </summary>
        internal static string UnableToConnectGameBoxNotFound {
            get {
                return ResourceManager.GetString("UnableToConnectGameBoxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open game. Game box &quot;{0}&quot; was not found in the library..
        /// </summary>
        internal static string UnableToOpenGame {
            get {
                return ResourceManager.GetString("UnableToOpenGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use saveas command..
        /// </summary>
        internal static string UseSaveasCommand {
            get {
                return ResourceManager.GetString("UseSaveasCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use saveasquit command..
        /// </summary>
        internal static string UseSaveasquitCommand {
            get {
                return ResourceManager.GetString("UseSaveasquitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of ZunTzu doesn&apos;t support voice communication when running Windows Vista..
        /// </summary>
        internal static string VistaWarningNoVoice {
            get {
                return ResourceManager.GetString("VistaWarningNoVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice connection failed..
        /// </summary>
        internal static string VoiceConnectionFailed {
            get {
                return ResourceManager.GetString("VoiceConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified compression type is not supported on the local computer..
        /// </summary>
        internal static string VoiceFailureCompressionNotSupported {
            get {
                return ResourceManager.GetString("VoiceFailureCompressionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client connected to a voice session that is incompatible with the host..
        /// </summary>
        internal static string VoiceFailureIncompatibleVersion {
            get {
                return ResourceManager.GetString("VoiceFailureIncompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session specified is not a voice session..
        /// </summary>
        internal static string VoiceFailureNoVoiceSession {
            get {
                return ResourceManager.GetString("VoiceFailureNoVoiceSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request to connect to the host failed..
        /// </summary>
        internal static string VoiceFailureOther {
            get {
                return ResourceManager.GetString("VoiceFailureOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified audio configuration has not been tested..
        /// </summary>
        internal static string VoiceFailureRunSetup {
            get {
                return ResourceManager.GetString("VoiceFailureRunSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure was encountered initializing the sound card..
        /// </summary>
        internal static string VoiceFailureSoundInitFailure {
            get {
                return ResourceManager.GetString("VoiceFailureSoundInitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed in the specified time..
        /// </summary>
        internal static string VoiceFailureTimeOut {
            get {
                return ResourceManager.GetString("VoiceFailureTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ZunTzu! Press Esc to begin..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re connected to host. Waiting for game data....
        /// </summary>
        internal static string YouAreConnected {
            get {
                return ResourceManager.GetString("YouAreConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re disconnected..
        /// </summary>
        internal static string YouAreDisconnected {
            get {
                return ResourceManager.GetString("YouAreDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now hosting..
        /// </summary>
        internal static string YouAreHosting {
            get {
                return ResourceManager.GetString("YouAreHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been disconnected. Game box &quot;{0}&quot; was not found in the library..
        /// </summary>
        internal static string YouHaveBeenDisconnectedGameBoxNotFound {
            get {
                return ResourceManager.GetString("YouHaveBeenDisconnectedGameBoxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ZunTzuBox {
            get {
                object obj = ResourceManager.GetObject("ZunTzuBox", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ZunTzuGame {
            get {
                object obj = ResourceManager.GetObject("ZunTzuGame", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
